/* Emoji catalog for the meme maker picker.
   Each item is [emoji, searchable name + keywords]. Grouped by category so
   the picker can render section headers; search flattens across all groups. */
window.EMOJIS = [
  {
    name: 'Smileys',
    items: [
      ['😀','grinning face happy'],['😃','grinning face big eyes happy'],['😄','grinning smiling eyes happy'],
      ['😁','beaming face smile happy'],['😆','grinning squinting laugh'],['😅','grinning sweat nervous laugh'],
      ['🤣','rolling on floor laughing rofl'],['😂','face tears of joy lol crying laugh'],['🙂','slightly smiling face'],
      ['🙃','upside down face silly'],['🫠','melting face'],['😉','winking face wink'],
      ['😊','smiling face blushing happy'],['😇','smiling halo angel'],['🥰','smiling hearts love'],
      ['😍','heart eyes love'],['🤩','star struck amazed'],['😘','blowing kiss love'],
      ['😗','kissing face'],['😚','kissing closed eyes'],['😙','kissing smiling eyes'],
      ['🥲','smiling with tear'],['😋','face savoring food yum'],['😛','face tongue out'],
      ['😜','winking tongue silly'],['🤪','zany face crazy'],['😝','squinting tongue'],
      ['🤑','money mouth rich'],['🤗','hugging face hug'],['🤭','hand over mouth giggle'],
      ['🫢','face open eyes hand mouth'],['🫣','face peeking'],['🤫','shushing quiet shh'],
      ['🤔','thinking face'],['🫡','saluting face salute respect'],['🤐','zipper mouth quiet'],
      ['🤨','face raised eyebrow suspicious'],['😐','neutral face'],['😑','expressionless face blank'],
      ['😶','face no mouth silent'],['🫥','dotted line face invisible'],['😶‍🌫️','face in clouds'],
      ['😏','smirking face smirk'],['😒','unamused face meh'],['🙄','rolling eyes'],
      ['😬','grimacing face awkward'],['😮‍💨','exhaling face relief'],['🤥','lying face pinocchio'],
      ['🫨','shaking face'],['😌','relieved face'],['😔','pensive face sad'],
      ['😪','sleepy face tired'],['🤤','drooling face'],['😴','sleeping zzz'],
      ['😷','face medical mask sick'],['🤒','face thermometer fever sick'],['🤕','face bandage hurt'],
      ['🤢','nauseated sick green'],['🤮','vomiting puke'],['🤧','sneezing face'],
      ['🥵','hot face sweating'],['🥶','cold face freezing'],['🥴','woozy drunk'],
      ['😵','face crossed eyes dizzy knockout'],['😵‍💫','face spiral eyes dizzy'],['🤯','exploding head mind blown'],
      ['🤠','cowboy hat'],['🥳','partying face celebrate'],['🥸','disguised face'],
      ['😎','smiling sunglasses cool'],['🤓','nerd face glasses'],['🧐','face monocle'],
      ['😕','confused face'],['🫤','diagonal mouth'],['😟','worried face'],
      ['🙁','slightly frowning'],['☹️','frowning face'],['😮','face open mouth surprised'],
      ['😯','hushed face'],['😲','astonished shocked'],['😳','flushed embarrassed'],
      ['🥺','pleading face begging'],['🥹','holding back tears'],['😦','frowning open mouth'],
      ['😧','anguished face'],['😨','fearful face scared'],['😰','anxious sweat'],
      ['😥','sad relieved'],['😢','crying face sad tear'],['😭','loudly crying bawling'],
      ['😱','face screaming fear'],['😖','confounded face'],['😣','persevering face'],
      ['😞','disappointed face'],['😓','downcast sweat'],['😩','weary face'],
      ['😫','tired face'],['🥱','yawning face'],['😤','face steam from nose angry determined'],
      ['😡','pouting red angry mad'],['😠','angry face'],['🤬','face cursing symbols mad'],
      ['😈','smiling imp devil evil'],['👿','angry imp devil'],['💀','skull death dead'],
      ['☠️','skull crossbones'],['💩','pile of poo poop'],['🤡','clown face creepy'],
      ['👹','ogre japanese demon'],['👺','goblin japanese'],['👻','ghost spooky boo'],
      ['👽','alien et'],['👾','space invader alien monster'],['🤖','robot bot'],
      ['😺','smiling cat happy'],['😸','grinning cat happy smile'],['😹','cat tears joy lol'],
      ['😻','heart eyes cat love'],['😼','smirking cat'],['😽','kissing cat'],
      ['🙀','weary cat shocked'],['😿','crying cat sad'],['😾','pouting cat angry'],
    ]
  },
  {
    name: 'People & Body',
    items: [
      ['👋','waving hand hi bye hello'],['🤚','raised back of hand stop'],['🖐️','hand fingers splayed five'],
      ['✋','raised hand high five stop'],['🖖','vulcan salute spock'],['🫱','rightwards hand'],
      ['🫲','leftwards hand'],['🫳','palm down hand'],['🫴','palm up hand'],
      ['👌','ok hand perfect'],['🤌','pinched fingers italian'],['🤏','pinching hand small'],
      ['✌️','victory peace hand'],['🤞','crossed fingers luck'],['🫰','hand index finger thumb money'],
      ['🤟','love you gesture ily'],['🤘','sign of the horns rock on'],['🤙','call me hand shaka hang loose'],
      ['👈','backhand index pointing left'],['👉','backhand index pointing right'],['👆','backhand index pointing up'],
      ['🖕','middle finger'],['👇','backhand index pointing down'],['☝️','index pointing up'],
      ['🫵','index pointing at viewer you'],['👍','thumbs up approve yes good'],['👎','thumbs down bad no'],
      ['✊','raised fist power'],['👊','oncoming fist bump punch'],['🤛','left facing fist'],
      ['🤜','right facing fist'],['👏','clapping hands applause'],['🙌','raising hands praise celebrate'],
      ['🫶','heart hands love'],['👐','open hands hug'],['🤲','palms up together praying'],
      ['🤝','handshake deal'],['🙏','folded hands pray thanks namaste'],['✍️','writing hand'],
      ['💅','nail polish'],['🤳','selfie'],['💪','flexed biceps muscle strong'],
      ['🦾','mechanical arm'],['🦿','mechanical leg'],['🦵','leg'],['🦶','foot'],
      ['👂','ear'],['🦻','ear with hearing aid'],['👃','nose'],['🫀','anatomical heart'],
      ['🫁','lungs'],['🧠','brain'],['🦷','tooth'],['🦴','bone'],
      ['👀','eyes looking'],['👁️','eye'],['👅','tongue'],['👄','mouth lips'],
      ['🫦','biting lip'],['💋','kiss mark lipstick'],
      ['👶','baby'],['🧒','child'],['👦','boy'],['👧','girl'],
      ['🧑','person'],['👨','man'],['👩','woman'],['🧔','bearded person'],
      ['👴','old man grandpa'],['👵','old woman grandma'],['🧓','older person'],
      ['👲','person with cap'],['👳','person with turban'],['🧕','woman with headscarf'],
      ['👮','police officer'],['👷','construction worker'],['💂','guard'],
      ['🕵️','detective spy'],['👰','bride'],['🤵','tuxedo groom'],
      ['🦸','superhero'],['🦹','supervillain'],['🧙','mage wizard'],
      ['🧚','fairy'],['🧛','vampire'],['🧜','merperson mermaid'],
      ['🧝','elf'],['🧞','genie'],['🧟','zombie'],
      ['💆','person getting massage'],['💇','person getting haircut'],['🚶','person walking'],
      ['🧍','person standing'],['🧎','person kneeling'],['🏃','person running'],
      ['💃','woman dancing'],['🕺','man dancing'],['🕴️','suspended man business'],
      ['👯','people with bunny ears'],['🧖','person in steamy room sauna'],['🧗','person climbing'],
    ]
  },
  {
    name: 'Animals & Nature',
    items: [
      ['🐶','dog face puppy'],['🐱','cat face kitty'],['🐭','mouse'],['🐹','hamster'],
      ['🐰','rabbit bunny'],['🦊','fox'],['🐻','bear'],['🐼','panda'],
      ['🐻‍❄️','polar bear'],['🐨','koala'],['🐯','tiger face'],['🦁','lion'],
      ['🐮','cow face'],['🐷','pig face'],['🐽','pig nose'],['🐸','frog pepe'],
      ['🐵','monkey face'],['🙈','see no evil monkey'],['🙉','hear no evil monkey'],
      ['🙊','speak no evil monkey'],['🐒','monkey'],['🐔','chicken'],['🐧','penguin'],
      ['🐦','bird'],['🐤','baby chick'],['🐣','hatching chick'],['🐥','front facing chick'],
      ['🦆','duck'],['🦅','eagle'],['🦉','owl'],['🦇','bat'],
      ['🐺','wolf'],['🐗','boar pig'],['🐴','horse face'],['🦄','unicorn'],
      ['🐝','bee honeybee'],['🐛','bug caterpillar'],['🦋','butterfly'],['🐌','snail'],
      ['🐞','lady bug'],['🐜','ant'],['🦟','mosquito'],['🪲','beetle'],
      ['🪳','cockroach'],['🕷️','spider'],['🕸️','spider web'],['🦂','scorpion'],
      ['🐢','turtle'],['🐍','snake'],['🦎','lizard'],['🦖','t-rex dinosaur'],
      ['🦕','sauropod dinosaur'],['🐙','octopus'],['🦑','squid'],['🦐','shrimp'],
      ['🦞','lobster'],['🦀','crab'],['🐡','blowfish'],['🐠','tropical fish'],
      ['🐟','fish'],['🐬','dolphin'],['🐳','spouting whale'],['🐋','whale'],
      ['🦈','shark'],['🐊','crocodile'],['🐅','tiger'],['🐆','leopard'],
      ['🦓','zebra'],['🦍','gorilla'],['🦧','orangutan'],['🐘','elephant'],
      ['🦣','mammoth'],['🦛','hippo'],['🦏','rhinoceros'],['🐪','camel'],
      ['🐫','two hump camel'],['🦒','giraffe'],['🦘','kangaroo'],['🐃','water buffalo'],
      ['🐂','ox bull'],['🐄','cow'],['🐎','horse running'],['🐖','pig'],
      ['🐏','ram'],['🐑','ewe sheep'],['🦙','llama'],['🐐','goat'],
      ['🦌','deer'],['🐕','dog'],['🐩','poodle'],['🦮','guide dog'],
      ['🐕‍🦺','service dog'],['🐈','cat'],['🐈‍⬛','black cat'],['🐓','rooster'],
      ['🦃','turkey'],['🦚','peacock'],['🦜','parrot'],['🦢','swan'],
      ['🪶','feather'],['🦩','flamingo'],['🐇','rabbit'],['🐁','mouse'],
      ['🐀','rat'],['🐿️','chipmunk'],['🦔','hedgehog'],['🦝','raccoon'],
      ['🦨','skunk'],['🦡','badger'],['🦦','otter'],['🦥','sloth'],
      ['🌵','cactus'],['🎄','christmas tree'],['🌲','evergreen tree pine'],['🌳','deciduous tree'],
      ['🌴','palm tree'],['🌱','seedling'],['🌿','herb'],['☘️','shamrock'],
      ['🍀','four leaf clover luck'],['🎍','pine decoration'],['🎋','tanabata tree'],['🍃','leaf fluttering wind'],
      ['🍂','fallen leaf'],['🍁','maple leaf'],['🍄','mushroom'],['🐚','spiral shell'],
      ['🪨','rock'],['🌾','sheaf of rice'],['💐','bouquet'],['🌷','tulip'],
      ['🌹','rose'],['🥀','wilted flower'],['🌺','hibiscus'],['🌸','cherry blossom'],
      ['🌼','blossom'],['🌻','sunflower'],['🌞','sun with face'],['🌝','full moon face'],
      ['🌛','first quarter moon face'],['🌜','last quarter moon face'],['🌚','new moon face'],
      ['🌕','full moon'],['🌖','waning gibbous moon'],['🌗','last quarter moon'],
      ['🌘','waning crescent moon'],['🌑','new moon'],['🌒','waxing crescent moon'],
      ['🌓','first quarter moon'],['🌔','waxing gibbous moon'],['🌙','crescent moon'],
      ['🌎','globe americas'],['🌍','globe europe africa'],['🌏','globe asia australia'],
      ['🪐','ringed planet saturn'],['💫','dizzy stars'],['⭐','star'],['🌟','glowing star'],
      ['✨','sparkles'],['⚡','high voltage lightning'],['☄️','comet'],['💥','collision boom'],
      ['🔥','fire flame lit'],['🌪️','tornado'],['🌈','rainbow'],['☀️','sun'],
      ['🌤️','sun behind small cloud'],['⛅','sun behind cloud'],['🌥️','sun behind large cloud'],
      ['☁️','cloud'],['🌦️','sun behind rain cloud'],['🌧️','cloud with rain'],
      ['⛈️','cloud with lightning rain'],['🌩️','cloud with lightning'],['🌨️','cloud with snow'],
      ['❄️','snowflake'],['☃️','snowman'],['⛄','snowman without snow'],['🌬️','wind face'],
      ['💨','dashing away'],['💧','droplet water'],['💦','sweat droplets'],['☔','umbrella with rain'],
      ['☂️','umbrella'],['🌊','water wave'],
    ]
  },
  {
    name: 'Food & Drink',
    items: [
      ['🍎','red apple'],['🍏','green apple'],['🍐','pear'],['🍊','tangerine orange'],
      ['🍋','lemon'],['🍌','banana'],['🍉','watermelon'],['🍇','grapes'],
      ['🍓','strawberry'],['🫐','blueberries'],['🍈','melon'],['🍒','cherries'],
      ['🍑','peach'],['🥭','mango'],['🍍','pineapple'],['🥥','coconut'],
      ['🥝','kiwi fruit'],['🍅','tomato'],['🍆','eggplant aubergine'],['🥑','avocado'],
      ['🥦','broccoli'],['🥬','leafy green'],['🥒','cucumber'],['🌶️','hot pepper chili'],
      ['🫑','bell pepper'],['🌽','corn'],['🥕','carrot'],['🫒','olive'],
      ['🧄','garlic'],['🧅','onion'],['🥔','potato'],['🍠','roasted sweet potato'],
      ['🥐','croissant'],['🥯','bagel'],['🍞','bread'],['🥖','baguette'],
      ['🫓','flatbread'],['🥨','pretzel'],['🧀','cheese wedge'],['🥚','egg'],
      ['🍳','cooking fried egg'],['🧈','butter'],['🥞','pancakes'],['🧇','waffle'],
      ['🥓','bacon'],['🥩','cut of meat steak'],['🍗','poultry leg'],['🍖','meat on bone'],
      ['🦴','bone'],['🌭','hot dog'],['🍔','hamburger'],['🍟','french fries'],
      ['🍕','pizza'],['🥪','sandwich'],['🥙','stuffed flatbread'],['🧆','falafel'],
      ['🌮','taco'],['🌯','burrito'],['🫔','tamale'],['🥗','green salad'],
      ['🥘','shallow pan food paella'],['🫕','fondue'],['🥫','canned food'],['🍝','spaghetti'],
      ['🍜','steaming bowl ramen'],['🍲','pot of food'],['🍛','curry rice'],['🍣','sushi'],
      ['🍱','bento box'],['🥟','dumpling'],['🦪','oyster'],['🍤','fried shrimp'],
      ['🍙','rice ball'],['🍚','cooked rice'],['🍘','rice cracker'],['🍥','fish cake swirl'],
      ['🥠','fortune cookie'],['🥮','moon cake'],['🍢','oden'],['🍡','dango'],
      ['🍧','shaved ice'],['🍨','ice cream'],['🍦','soft ice cream'],['🥧','pie'],
      ['🧁','cupcake'],['🍰','shortcake slice'],['🎂','birthday cake'],['🍮','custard'],
      ['🍭','lollipop'],['🍬','candy'],['🍫','chocolate bar'],['🍿','popcorn'],
      ['🍩','doughnut donut'],['🍪','cookie'],['🌰','chestnut'],['🥜','peanuts'],
      ['🍯','honey pot'],['🥛','glass of milk'],['🍼','baby bottle'],['☕','hot beverage coffee'],
      ['🍵','teacup without handle tea'],['🧉','mate'],['🧃','beverage box juice'],['🥤','cup with straw'],
      ['🧋','bubble tea'],['🍶','sake'],['🍺','beer mug'],['🍻','clinking beer mugs cheers'],
      ['🥂','clinking glasses toast'],['🍷','wine glass'],['🥃','tumbler glass whiskey'],['🍸','cocktail'],
      ['🍹','tropical drink'],['🍾','bottle with popping cork champagne'],['🧊','ice cube'],
      ['🥄','spoon'],['🍴','fork and knife'],['🍽️','fork and knife with plate'],['🥣','bowl with spoon'],
      ['🥡','takeout box'],['🥢','chopsticks'],['🧂','salt'],
    ]
  },
  {
    name: 'Activities',
    items: [
      ['⚽','soccer ball football'],['🏀','basketball'],['🏈','american football'],['⚾','baseball'],
      ['🥎','softball'],['🎾','tennis'],['🏐','volleyball'],['🏉','rugby'],
      ['🥏','flying disc frisbee'],['🎱','pool 8 ball billiards'],['🪀','yo-yo'],['🏓','ping pong'],
      ['🏸','badminton'],['🏒','ice hockey'],['🏑','field hockey'],['🥍','lacrosse'],
      ['🏏','cricket'],['🪃','boomerang'],['🥅','goal net'],['⛳','flag in hole golf'],
      ['🪁','kite'],['🏹','bow and arrow archery'],['🎣','fishing pole'],['🤿','diving mask'],
      ['🥊','boxing glove'],['🥋','martial arts uniform'],['🎽','running shirt'],['🛹','skateboard'],
      ['🛼','roller skate'],['🛷','sled'],['⛸️','ice skate'],['🥌','curling stone'],
      ['🎿','skis'],['⛷️','skier'],['🏂','snowboarder'],['🪂','parachute'],
      ['🏋️','person lifting weights'],['🤼','people wrestling'],['🤸','person cartwheeling'],
      ['⛹️','person bouncing ball basketball'],['🤺','fencer'],['🤾','person playing handball'],
      ['🏌️','golfer'],['🏇','horse racing'],['🧘','person lotus meditation'],
      ['🏄','surfer'],['🏊','swimmer'],['🤽','water polo'],['🚣','person rowing boat'],
      ['🧗','climber'],['🚵','mountain biker'],['🚴','biker cyclist'],['🏆','trophy'],
      ['🥇','gold medal'],['🥈','silver medal'],['🥉','bronze medal'],['🏅','sports medal'],
      ['🎖️','military medal'],['🏵️','rosette'],['🎗️','reminder ribbon'],['🎫','ticket'],
      ['🎟️','admission tickets'],['🎪','circus tent'],['🤹','juggler'],['🎭','performing arts masks'],
      ['🩰','ballet shoes'],['🎨','artist palette'],['🎬','clapper board movie'],['🎤','microphone'],
      ['🎧','headphone'],['🎼','musical score'],['🎹','musical keyboard piano'],['🥁','drum'],
      ['🪘','long drum'],['🎷','saxophone'],['🎺','trumpet'],['🪗','accordion'],
      ['🎸','guitar'],['🪕','banjo'],['🎻','violin'],['🎲','game die dice'],
      ['♟️','chess pawn'],['🎯','direct hit bullseye target'],['🎳','bowling'],['🎮','video game'],
      ['🕹️','joystick'],['🎰','slot machine'],['🧩','puzzle piece'],
    ]
  },
  {
    name: 'Travel & Places',
    items: [
      ['🚗','car automobile'],['🚕','taxi'],['🚙','sport utility vehicle suv'],['🚌','bus'],
      ['🚎','trolleybus'],['🏎️','racing car'],['🚓','police car'],['🚑','ambulance'],
      ['🚒','fire engine'],['🚐','minibus'],['🛻','pickup truck'],['🚚','delivery truck'],
      ['🚛','articulated lorry'],['🚜','tractor'],['🛵','motor scooter'],['🏍️','motorcycle'],
      ['🛺','auto rickshaw'],['🚲','bicycle'],['🛴','kick scooter'],['🛹','skateboard'],
      ['🛼','roller skate'],['🚨','police car light siren'],['🚔','oncoming police car'],
      ['🚍','oncoming bus'],['🚘','oncoming automobile'],['🚖','oncoming taxi'],
      ['🚡','aerial tramway'],['🚠','mountain cableway'],['🚟','suspension railway'],
      ['🚃','railway car'],['🚋','tram car'],['🚞','mountain railway'],['🚝','monorail'],
      ['🚄','high speed train'],['🚅','bullet train'],['🚈','light rail'],['🚂','locomotive'],
      ['🚆','train'],['🚇','metro'],['🚊','tram'],['🚉','station'],
      ['✈️','airplane'],['🛫','airplane departure'],['🛬','airplane arrival'],['🛩️','small airplane'],
      ['💺','seat'],['🛰️','satellite'],['🚀','rocket launch'],['🛸','flying saucer ufo'],
      ['🚁','helicopter'],['🛶','canoe'],['⛵','sailboat'],['🚤','speedboat'],
      ['🛥️','motor boat'],['🛳️','passenger ship'],['⛴️','ferry'],['🚢','ship'],
      ['⚓','anchor'],['🪝','hook'],['⛽','fuel pump'],['🚧','construction'],
      ['🚦','vertical traffic light'],['🚥','horizontal traffic light'],['🗺️','world map'],
      ['🗿','moai statue'],['🗽','statue of liberty'],['🗼','tokyo tower'],['🏰','castle'],
      ['🏯','japanese castle'],['🏟️','stadium'],['🎡','ferris wheel'],['🎢','roller coaster'],
      ['🎠','carousel horse'],['⛲','fountain'],['⛱️','umbrella on ground beach'],['🏖️','beach with umbrella'],
      ['🏝️','desert island'],['🏜️','desert'],['🌋','volcano'],['⛰️','mountain'],
      ['🏔️','snow capped mountain'],['🗻','mount fuji'],['🏕️','camping'],['⛺','tent'],
      ['🏠','house'],['🏡','house with garden'],['🏘️','houses'],['🏚️','derelict house'],
      ['🏗️','building construction'],['🏭','factory'],['🏢','office building'],['🏬','department store'],
      ['🏣','japanese post office'],['🏤','post office'],['🏥','hospital'],['🏦','bank'],
      ['🏨','hotel'],['🏪','convenience store'],['🏫','school'],['🏩','love hotel'],
      ['💒','wedding'],['🏛️','classical building'],['⛪','church'],['🕌','mosque'],
      ['🕍','synagogue'],['🛕','hindu temple'],['⛩️','shinto shrine'],['🕋','kaaba'],
      ['⛩️','shinto shrine'],['🌁','foggy'],['🌃','night with stars'],['🏙️','cityscape'],
      ['🌄','sunrise over mountains'],['🌅','sunrise'],['🌆','cityscape dusk'],['🌇','sunset'],
      ['🌉','bridge at night'],['♨️','hot springs'],['🎑','moon viewing ceremony'],
    ]
  },
  {
    name: 'Objects',
    items: [
      ['⌚','watch'],['📱','mobile phone'],['📲','mobile phone arrow'],['💻','laptop'],
      ['⌨️','keyboard'],['🖥️','desktop computer'],['🖨️','printer'],['🖱️','computer mouse'],
      ['🖲️','trackball'],['🕹️','joystick'],['🗜️','clamp'],['💽','computer disk'],
      ['💾','floppy disk save'],['💿','optical disk cd'],['📀','dvd'],['📼','videocassette'],
      ['📷','camera'],['📸','camera flash'],['📹','video camera'],['🎥','movie camera'],
      ['📽️','film projector'],['🎞️','film frames'],['📞','telephone receiver'],['☎️','telephone'],
      ['📟','pager'],['📠','fax machine'],['📺','television'],['📻','radio'],
      ['🎙️','studio microphone'],['🎚️','level slider'],['🎛️','control knobs'],['🧭','compass'],
      ['⏱️','stopwatch'],['⏲️','timer clock'],['⏰','alarm clock'],['🕰️','mantelpiece clock'],
      ['⌛','hourglass done'],['⏳','hourglass not done'],['📡','satellite antenna'],['🔋','battery'],
      ['🪫','low battery'],['🔌','electric plug'],['💡','light bulb idea'],['🔦','flashlight'],
      ['🕯️','candle'],['🪔','diya lamp'],['🧯','fire extinguisher'],['🛢️','oil drum'],
      ['💸','money with wings dollar'],['💵','dollar banknote cash'],['💴','yen banknote'],
      ['💶','euro banknote'],['💷','pound banknote'],['💰','money bag'],['🪙','coin'],
      ['💳','credit card'],['💎','gem stone diamond'],['⚖️','balance scale'],['🪜','ladder'],
      ['🧰','toolbox'],['🔧','wrench'],['🔨','hammer'],['⚒️','hammer and pick'],
      ['🛠️','hammer and wrench'],['⛏️','pick'],['🪚','saw'],['🔩','nut and bolt'],
      ['⚙️','gear settings'],['🪤','mouse trap'],['🧱','brick'],['⛓️','chains'],
      ['🧲','magnet'],['🔫','water pistol'],['💣','bomb'],['🧨','firecracker'],
      ['🪓','axe'],['🔪','kitchen knife'],['🗡️','dagger'],['⚔️','crossed swords'],
      ['🛡️','shield'],['🚬','cigarette'],['⚰️','coffin'],['🪦','headstone'],
      ['⚱️','funeral urn'],['🏺','amphora'],['🔮','crystal ball'],['🪄','magic wand'],
      ['📿','prayer beads'],['🧿','nazar amulet'],['💈','barber pole'],['⚗️','alembic'],
      ['🔭','telescope'],['🔬','microscope'],['🕳️','hole'],['🩹','adhesive bandage'],
      ['🩺','stethoscope'],['💊','pill'],['💉','syringe'],['🩸','drop of blood'],
      ['🧬','dna'],['🦠','microbe virus'],['🧫','petri dish'],['🧪','test tube'],
      ['🌡️','thermometer'],['🧹','broom'],['🧺','basket'],['🧻','roll of paper toilet'],
      ['🚽','toilet'],['🚰','potable water'],['🚿','shower'],['🛁','bathtub'],
      ['🛀','person taking bath'],['🧼','soap'],['🪒','razor'],['🧽','sponge'],
      ['🪣','bucket'],['🧴','lotion bottle'],['🔑','key'],['🗝️','old key'],
      ['🚪','door'],['🪑','chair'],['🛋️','couch and lamp'],['🛏️','bed'],
      ['🛌','person in bed'],['🧸','teddy bear'],['🖼️','framed picture'],['🪞','mirror'],
      ['🪟','window'],['🛍️','shopping bags'],['🛒','shopping cart'],['🎁','wrapped gift'],
      ['🎈','balloon'],['🎏','carp streamer'],['🎀','ribbon'],['🎊','confetti ball'],
      ['🎉','party popper'],['🎎','japanese dolls'],['🏮','red paper lantern'],['🎐','wind chime'],
      ['🧧','red envelope'],['✉️','envelope mail'],['📩','envelope with arrow'],['📨','incoming envelope'],
      ['📧','email'],['💌','love letter'],['📮','postbox'],['📪','closed mailbox lowered flag'],
      ['📫','closed mailbox raised flag'],['📬','open mailbox raised flag'],['📭','open mailbox lowered flag'],
      ['📦','package'],['📯','postal horn'],['📥','inbox tray'],['📤','outbox tray'],
      ['📜','scroll'],['📃','page with curl'],['📑','bookmark tabs'],['🧾','receipt'],
      ['📊','bar chart'],['📈','chart increasing'],['📉','chart decreasing'],['📄','page facing up'],
      ['📅','calendar'],['📆','tear-off calendar'],['🗒️','spiral notepad'],['🗓️','spiral calendar'],
      ['📇','card index'],['🗃️','card file box'],['🗳️','ballot box with ballot'],['🗄️','file cabinet'],
      ['📋','clipboard'],['📁','file folder'],['📂','open file folder'],['🗂️','card index dividers'],
      ['🗞️','rolled up newspaper'],['📰','newspaper'],['📓','notebook'],['📔','notebook with decorative cover'],
      ['📒','ledger'],['📕','closed book'],['📗','green book'],['📘','blue book'],
      ['📙','orange book'],['📚','books'],['📖','open book'],['🔖','bookmark'],
      ['🧷','safety pin'],['🔗','link'],['📎','paperclip'],['🖇️','linked paperclips'],
      ['📐','triangular ruler'],['📏','straight ruler'],['🧮','abacus'],['📌','pushpin'],
      ['📍','round pushpin'],['✂️','scissors'],['🖊️','pen'],['🖋️','fountain pen'],
      ['✒️','black nib'],['🖌️','paintbrush'],['🖍️','crayon'],['📝','memo pencil'],
      ['✏️','pencil'],['🔍','magnifying glass tilted left'],['🔎','magnifying glass tilted right'],
      ['🔏','locked with pen'],['🔐','locked with key'],['🔒','locked'],['🔓','unlocked'],
    ]
  },
  {
    name: 'Symbols',
    items: [
      ['❤️','red heart'],['🧡','orange heart'],['💛','yellow heart'],['💚','green heart'],
      ['💙','blue heart'],['💜','purple heart'],['🖤','black heart'],['🤍','white heart'],
      ['🤎','brown heart'],['💔','broken heart'],['❣️','heart exclamation'],['💕','two hearts'],
      ['💞','revolving hearts'],['💓','beating heart'],['💗','growing heart'],['💖','sparkling heart'],
      ['💘','heart with arrow'],['💝','heart with ribbon'],['💟','heart decoration'],['♥️','heart suit'],
      ['💌','love letter'],['💋','kiss mark'],['💯','hundred points'],['💢','anger symbol'],
      ['💥','collision'],['💫','dizzy'],['💦','sweat droplets'],['💨','dashing away'],
      ['🕳️','hole'],['💣','bomb'],['💬','speech balloon'],['👁️‍🗨️','eye in speech bubble'],
      ['🗨️','left speech bubble'],['🗯️','right anger bubble'],['💭','thought balloon'],['💤','zzz sleep'],
      ['🔴','red circle'],['🟠','orange circle'],['🟡','yellow circle'],['🟢','green circle'],
      ['🔵','blue circle'],['🟣','purple circle'],['⚫','black circle'],['⚪','white circle'],
      ['🟤','brown circle'],['🟥','red square'],['🟧','orange square'],['🟨','yellow square'],
      ['🟩','green square'],['🟦','blue square'],['🟪','purple square'],['⬛','black large square'],
      ['⬜','white large square'],['🟫','brown square'],['◼️','black medium square'],['◻️','white medium square'],
      ['◾','black medium small square'],['◽','white medium small square'],['▪️','black small square'],
      ['▫️','white small square'],['🔶','large orange diamond'],['🔷','large blue diamond'],
      ['🔸','small orange diamond'],['🔹','small blue diamond'],['🔺','red triangle pointed up'],
      ['🔻','red triangle pointed down'],['💠','diamond with dot'],['🔘','radio button'],
      ['🔳','white square button'],['🔲','black square button'],
      ['♠️','spade suit'],['♣️','club suit'],['♦️','diamond suit'],
      ['✅','check mark button'],['☑️','check box with check'],['✔️','check mark'],
      ['❌','cross mark'],['❎','cross mark button'],['➕','plus'],['➖','minus'],
      ['➗','divide'],['✖️','multiply'],['🟰','heavy equals'],['♾️','infinity'],
      ['‼️','double exclamation'],['⁉️','exclamation question'],['❓','red question mark'],
      ['❔','white question mark'],['❗','red exclamation mark'],['❕','white exclamation mark'],
      ['〽️','part alternation'],['⚠️','warning'],['🚸','children crossing'],['🔱','trident'],
      ['⚜️','fleur de lis'],['🔰','japanese symbol beginner'],['♻️','recycling'],['✳️','eight spoked asterisk'],
      ['✴️','eight pointed star'],['❇️','sparkle'],['©️','copyright'],['®️','registered'],
      ['™️','trade mark'],['#️⃣','keycap number sign'],['*️⃣','keycap asterisk'],
      ['0️⃣','keycap zero'],['1️⃣','keycap one'],['2️⃣','keycap two'],['3️⃣','keycap three'],
      ['4️⃣','keycap four'],['5️⃣','keycap five'],['6️⃣','keycap six'],['7️⃣','keycap seven'],
      ['8️⃣','keycap eight'],['9️⃣','keycap nine'],['🔟','keycap ten'],
      ['⬆️','up arrow'],['↗️','up-right arrow'],['➡️','right arrow'],['↘️','down-right arrow'],
      ['⬇️','down arrow'],['↙️','down-left arrow'],['⬅️','left arrow'],['↖️','up-left arrow'],
      ['↕️','up down arrow'],['↔️','left right arrow'],['↩️','right arrow curving left'],
      ['↪️','left arrow curving right'],['⤴️','right arrow curving up'],['⤵️','right arrow curving down'],
      ['🔃','clockwise vertical arrows'],['🔄','counterclockwise arrows'],['🔙','back arrow'],
      ['🔚','end arrow'],['🔛','on arrow'],['🔜','soon arrow'],['🔝','top arrow'],
      ['🔀','shuffle tracks'],['🔁','repeat'],['🔂','repeat single'],['▶️','play button'],
      ['⏸️','pause button'],['⏯️','play or pause'],['⏹️','stop button'],['⏺️','record button'],
      ['⏭️','next track'],['⏮️','last track'],['⏩','fast forward'],['⏪','fast reverse'],
      ['⏫','fast up'],['⏬','fast down'],['◀️','reverse button'],['🔼','upwards button'],
      ['🔽','downwards button'],['🔅','dim button'],['🔆','bright button'],['📶','antenna bars'],
      ['📳','vibration mode'],['📴','mobile phone off'],['🔇','muted speaker'],['🔈','speaker low'],
      ['🔉','speaker medium'],['🔊','speaker high'],['🔔','bell'],['🔕','bell with slash'],
      ['📣','megaphone'],['📢','loudspeaker'],['👁️','eye'],['🕉️','om'],
      ['✡️','star of david'],['☸️','wheel of dharma'],['☯️','yin yang'],['✝️','latin cross'],
      ['☦️','orthodox cross'],['☪️','star and crescent'],['☮️','peace symbol'],['🕎','menorah'],
      ['🔯','dotted six pointed star'],['♈','aries'],['♉','taurus'],['♊','gemini'],
      ['♋','cancer'],['♌','leo'],['♍','virgo'],['♎','libra'],
      ['♏','scorpio'],['♐','sagittarius'],['♑','capricorn'],['♒','aquarius'],
      ['♓','pisces'],['⛎','ophiuchus'],
    ]
  },
  {
    name: 'Flags',
    items: [
      ['🏳️','white flag'],['🏴','black flag'],['🏁','chequered flag'],['🚩','triangular flag'],
      ['🏳️‍🌈','rainbow flag pride'],['🏳️‍⚧️','transgender flag'],['🏴‍☠️','pirate flag'],
      ['🇺🇸','united states us usa america'],['🇬🇧','united kingdom uk britain'],['🇨🇦','canada'],
      ['🇦🇺','australia'],['🇯🇵','japan'],['🇰🇷','south korea'],['🇨🇳','china'],
      ['🇮🇳','india'],['🇧🇷','brazil'],['🇲🇽','mexico'],['🇩🇪','germany'],
      ['🇫🇷','france'],['🇮🇹','italy'],['🇪🇸','spain'],['🇵🇹','portugal'],
      ['🇷🇺','russia'],['🇺🇦','ukraine'],['🇵🇱','poland'],['🇳🇱','netherlands'],
      ['🇧🇪','belgium'],['🇨🇭','switzerland'],['🇸🇪','sweden'],['🇳🇴','norway'],
      ['🇩🇰','denmark'],['🇫🇮','finland'],['🇮🇪','ireland'],['🇬🇷','greece'],
      ['🇹🇷','turkey'],['🇮🇱','israel'],['🇸🇦','saudi arabia'],['🇦🇪','united arab emirates uae'],
      ['🇿🇦','south africa'],['🇪🇬','egypt'],['🇳🇬','nigeria'],['🇰🇪','kenya'],
      ['🇦🇷','argentina'],['🇨🇱','chile'],['🇨🇴','colombia'],['🇵🇪','peru'],
      ['🇻🇪','venezuela'],['🇹🇭','thailand'],['🇻🇳','vietnam'],['🇵🇭','philippines'],
      ['🇮🇩','indonesia'],['🇲🇾','malaysia'],['🇸🇬','singapore'],['🇳🇿','new zealand'],
      ['🇮🇸','iceland'],['🇦🇹','austria'],['🇨🇿','czech republic'],['🇭🇺','hungary'],
      ['🇷🇴','romania'],['🇪🇺','european union eu'],
    ]
  },
];
