"""Regenerate templates/templates.json from images in templates/classic and templates/animal.

Templates are loaded one at a time as a canvas background (not all preloaded like
stickers), so this manifest is filename-only — no base64 embedding. Same-origin
URLs keep the canvas un-tainted so Download/Copy/Share still work.

Run after adding/removing template images:  python update-templates.py
"""
import hashlib
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
TEMPLATES_DIR = os.path.join(ROOT, "templates")
CATEGORIES = ["classic", "animal", "gifs"]
IMG_RE = re.compile(r"\.(png|jpe?g|webp|gif|svg|avif)$", re.I)


def pretty_name(filename: str) -> str:
    stem = os.path.splitext(filename)[0]
    words = re.split(r"[-_\s]+", stem)
    return " ".join(w[:1].upper() + w[1:] for w in words if w)


def scan(category: str) -> list[dict]:
    folder = os.path.join(TEMPLATES_DIR, category)
    if not os.path.isdir(folder):
        return []
    names = sorted(
        (
            f
            for f in os.listdir(folder)
            if os.path.isfile(os.path.join(folder, f)) and IMG_RE.search(f)
        ),
        key=str.lower,
    )
    entries = []
    for n in names:
        entry = {
            "name": pretty_name(n),
            "file": n,
            "src": f"templates/{category}/{n}",
            "category": category,
        }
        # If a matching thumb exists (static first-frame PNG for GIFs), point
        # the picker at it so the grid stays fast and doesn't spin up dozens
        # of simultaneous GIF decoders. See make-gif-thumbs.py.
        stem, _ = os.path.splitext(n)
        thumb_path = os.path.join(folder, "thumbs", stem + ".png")
        if os.path.isfile(thumb_path):
            entry["thumb"] = f"templates/{category}/thumbs/{stem}.png"
        entries.append(entry)
    return entries


def main() -> int:
    os.makedirs(TEMPLATES_DIR, exist_ok=True)
    for c in CATEGORIES:
        os.makedirs(os.path.join(TEMPLATES_DIR, c), exist_ok=True)

    grouped = {c: scan(c) for c in CATEGORIES}
    flat = [t for c in CATEGORIES for t in grouped[c]]

    out = {
        "note": "Auto-generated by update-templates.py. Edit templates/classic or templates/animal and re-run.",
        "categories": CATEGORIES,
        "templates": flat,
    }
    payload = json.dumps(out, indent=2) + "\n"

    # templates.json — filename-only manifest, used as a fetch fallback.
    json_path = os.path.join(TEMPLATES_DIR, "templates.json")
    with open(json_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(payload)

    # templates.js — window.EMOTEMPLATES, loaded via <script> so it works
    # under file:// (browsers block fetch to local files). Thumbnails stay as
    # plain same-origin URLs — no base64 embedding, so this file stays tiny.
    js_path = os.path.join(TEMPLATES_DIR, "templates.js")
    js_body = (
        "/* Auto-generated. Do not edit by hand.\n"
        "   Drop images into templates/classic or templates/animal and run:\n"
        "     python update-templates.py */\n"
        f"window.EMOTEMPLATES = {json.dumps({'categories': CATEGORIES, 'templates': flat})};\n"
    )
    with open(js_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(js_body)

    # Cache-bust: stamp meme-maker.html's <script src="templates/templates.js?v=..">.
    version = hashlib.md5(js_body.encode("utf-8")).hexdigest()[:10]
    meme_path = os.path.join(ROOT, "meme-maker.html")
    if os.path.isfile(meme_path):
        with open(meme_path, "r", encoding="utf-8") as f:
            html = f.read()
        new_html, n = re.subn(
            r'<script src="templates/templates\.js(?:\?v=[^"]*)?"',
            f'<script src="templates/templates.js?v={version}"',
            html,
            count=1,
        )
        if n and new_html != html:
            with open(meme_path, "w", encoding="utf-8", newline="\n") as f:
                f.write(new_html)
            print(f"Stamped meme-maker.html with templates.js?v={version}")

    for c in CATEGORIES:
        print(f"{c}: {len(grouped[c])} template(s)")
        for t in grouped[c]:
            print(f"  - {t['name']} ({t['file']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
