"""Regenerate stickers/stickers.js (and .json) from images in /stickers.

Each image is embedded as a base64 data URL so the meme maker's canvas export works
under both file:// (local testing) and HTTP (GitHub Pages) — canvas tainting only
blocks exports when images come from cross-origin sources, and data: URLs are always
safe. Run after adding new sticker images:  python update-stickers.py
"""
import base64
import hashlib
import json
import mimetypes
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
STICKERS_DIR = os.path.join(ROOT, "stickers")
IMG_RE = re.compile(r"\.(png|jpe?g|webp|gif|svg|avif)$", re.I)
MIME_MAP = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
    ".gif": "image/gif",
    ".svg": "image/svg+xml",
    ".avif": "image/avif",
}


def data_url(path: str) -> str:
    ext = os.path.splitext(path)[1].lower()
    mime = MIME_MAP.get(ext) or mimetypes.guess_type(path)[0] or "application/octet-stream"
    with open(path, "rb") as f:
        b64 = base64.b64encode(f.read()).decode("ascii")
    return f"data:{mime};base64,{b64}"


def main() -> int:
    if not os.path.isdir(STICKERS_DIR):
        print(f"error: {STICKERS_DIR} not found", file=sys.stderr)
        return 1

    names = sorted(
        (
            f
            for f in os.listdir(STICKERS_DIR)
            if os.path.isfile(os.path.join(STICKERS_DIR, f))
            and IMG_RE.search(f)
            and f not in {"stickers.json", "stickers.js"}
        ),
        key=str.lower,
    )

    entries = []
    total_bytes = 0
    for name in names:
        path = os.path.join(STICKERS_DIR, name)
        size = os.path.getsize(path)
        total_bytes += size
        entries.append({"name": name, "src": data_url(path)})

    js_path = os.path.join(STICKERS_DIR, "stickers.js")
    json_path = os.path.join(STICKERS_DIR, "stickers.json")

    # stickers.js — embedded data URLs, used by the meme maker at runtime.
    # Entry shape is {name, src} where src is a data: URL (always same-origin for canvas).
    js_body = (
        "/* Auto-generated. Do not edit by hand.\n"
        "   Add files to /stickers and either push (GitHub Action rebuilds this)\n"
        "   or run: python update-stickers.py */\n"
        "window.EMOSTICKERS = " + json.dumps(entries) + ";\n"
    )
    with open(js_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(js_body)

    # stickers.json — filenames-only fallback, lightweight, for tooling/inspection.
    with open(json_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(
            {
                "note": "Auto-generated by update-stickers.py. Filenames only; runtime uses stickers.js.",
                "stickers": names,
            },
            f,
            indent=2,
        )
        f.write("\n")

    # Cache-bust: stamp meme-maker.html's <script src="stickers/stickers.js"> with a
    # content hash so GitHub Pages / browser caches pick up new stickers immediately.
    version = hashlib.md5(js_body.encode("utf-8")).hexdigest()[:10]
    meme_path = os.path.join(ROOT, "meme-maker.html")
    if os.path.isfile(meme_path):
        with open(meme_path, "r", encoding="utf-8") as f:
            html = f.read()
        new_html, n = re.subn(
            r'<script src="stickers/stickers\.js(?:\?v=[^"]*)?"',
            f'<script src="stickers/stickers.js?v={version}"',
            html,
            count=1,
        )
        if n and new_html != html:
            with open(meme_path, "w", encoding="utf-8", newline="\n") as f:
                f.write(new_html)
            print(f"Stamped meme-maker.html with ?v={version}")

    kb = total_bytes / 1024
    print(f"Wrote {len(names)} stickers to stickers.js ({kb:.0f} KB raw):")
    for n in names:
        print(f"  - {n}")
    if total_bytes > 4 * 1024 * 1024:
        print("warning: stickers.js will be large (>4MB). Consider smaller PNGs.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
